### ISSUE TITLE
動画のOGP用に「はてなセリフ」的なものを作る

### ISSUE THREAD

**Issue by lestrrat** [builderscon/multimedia-tools#1]
こういうのなるたけ自動的に作りたい https://i.ytimg.com/vi/9XTl1d4nwdY/hqdefault.jpg
できればGAEで簡単に動くように、python 2.7かGo 1.6.4（もしくGAEがサポートしてる他の言語）でやりたい

* セッションタイトル
* 発表者名
* イベント名
* builderscon.io へのリンク
* 発表者画像

をがっちゃんこするアプリが欲しい。

動作UI的には、

* トークのURLを入力する
* 発表者画像をアップロードする

…とすると、がっちゃんこされた画像が表示される、っての作りたい

**Comment by koron** [comment]
要件を明確にするために:

ガッチャンコした結果画像は、どこに置くんですかね?
* 同一Webアプリ上でホスト
* どこか外部のストレージ

**Comment by lestrrat** [comment]
ダウンロードする（つまり結果は保持しない）、でいいと思います。最終的にはYoutubeにあげるので。

**Comment by hasegawa-tomoki** [comment]
> もしくGAEがサポートしてる他の言語

来ましたよ、 uzulla さん。
（とか言いつつ、明確にPHPにメリットがある要件でも無いので、GoかPythonで良いと思うけど）

**Comment by lestrrat** [comment]
ちなみにこれ、8中旬〜8末くらいまでにできてると最高

**Comment by lestrrat** [comment]
ちなみに、APIとつなぎこむのは面倒なので、とりあえずなんか定型のJSONとがっちゃんこ、っていうレベルまでできてればあとはつなぎこむのはぼくがやってもいいです

**Comment by lestrrat** [comment]
add builderscon logo

**Comment by lestrrat** [comment]
@dictav さんの手により、JS/Canvasバージョンが爆誕し、世の中が平和になった。
